version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=DB # Replace with your configuration
      - DB_USER=USER
      - DB_PASSWORD=PASSWORD
      - DB_NAME=DB
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: USER # Replace with your configuration
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/pgsql/data

volumes:
  db_data: